Repository AY2425S1-CS2103T-F12-2/tp, pull requests merged in 2024-11, with the labels that each got.

#141 Update Command History
  src/main/java/seedu/address/ui/CommandHistory.java
  src/test/java/seedu/address/ui/CommandHistoryTest.java
Labels: priority.Medium

#151 Update User Guide to include Parameter details and glossary
  docs/UserGuide.md
Labels: severity.VeryLow

#164 Update UserGuide
  docs/UserGuide.md
Labels: alpha-bug

#142 Modified Person::isSamePerson check
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Student.java
  src/main/java/seedu/address/model/person/Teacher.java
  src/test/java/seedu/address/logic/commands/RedoCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/StudentTest.java
  src/test/java/seedu/address/model/person/TeacherTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
Labels: alpha-bug

#154 Alpha Bug Fix: Update success messages and errors depending on what gets cleared in Clear command
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
Labels: alpha-bug

#157 Alpha Bug Fix: Clear and Find throw error messages when no keywords are given for a tag
  src/main/java/seedu/address/model/person/PersonContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: alpha-bug

#158 Alpha Bug Fix: Update user guide URL in help window
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: alpha-bug

#150 Edit Phone::isValidPhone
  src/main/java/seedu/address/model/person/Phone.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/AddressContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/EmailContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PhoneContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
  src/test/java/seedu/address/model/person/TagContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: alpha-bug

#149 Add duplicate index handling for bulk DeleteCommand
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
Labels: alpha-bug

#162 Alpha Bug Fix: Update PersonContainsKeywordsPredicate to account for Subject and Classes
  src/main/java/seedu/address/model/person/ClassContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/PersonContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/SubjectContainsKeywordsPredicate.java
  src/test/java/seedu/address/model/person/ClassContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PersonContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/SubjectContainsKeywordsPredicateTest.java
Labels: alpha-bug

#166 Fix sort command to handle class sorting correctly
  src/main/java/seedu/address/commons/util/ClassComparatorUtil.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/test/java/seedu/address/commons/util/ClassComparatorUtilTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
Labels: alpha-bug

#165 Update Student with Next-of-Kin Details
  src/main/java/seedu/address/logic/commands/AddStudentCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddStudentCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Student.java
  src/main/java/seedu/address/model/person/Teacher.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddStudentCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/StudentBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#174 Fixing Alpha bugs for attendance marking
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/UnmarkAttendanceCommand.java
  src/main/java/seedu/address/logic/parser/UnmarkAttendanceCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Student.java
  src/main/java/seedu/address/model/person/Teacher.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/UnmarkAttendanceCommandTest.java
  src/test/java/seedu/address/logic/parser/UnmarkAttendanceCommandParserTest.java
  src/test/java/seedu/address/model/person/DaysAttendedTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/StudentTest.java
  src/test/java/seedu/address/model/person/TeacherTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/Assert.java
Labels: alpha-bug

#173 Fix Alpha Bugs to improve find functionality
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/model/person/GenderContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/PersonContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/model/person/GenderContainsKeywordsPredicateTest.java
Labels: alpha-bug

#176 Update user guide with new sort and attendance functionality
  docs/UserGuide.md
Labels: priority.High

#179 Add defensive coding techniques
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkAttendanceCommand.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/logic/parser/UnmarkAttendanceCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/DaysAttended.java
Labels: priority.High

#187 Update UG and Edit command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
Labels: priority.Medium

#191 Update code quality
  src/main/java/seedu/address/commons/util/ComparatorUtil.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/MarkAttendanceCommand.java
  src/main/java/seedu/address/logic/commands/ResetAttendanceCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkAttendanceCommand.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/logic/parser/UnmarkAttendanceCommandParser.java
  src/main/java/seedu/address/model/person/DaysAttended.java
  src/main/java/seedu/address/model/person/Teacher.java
  src/test/java/seedu/address/commons/util/ComparatorUtilTest.java
  src/test/java/seedu/address/logic/commands/MarkAttendanceCommandTest.java
  src/test/java/seedu/address/logic/commands/ResetAttendanceCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/commands/UnmarkAttendanceCommandTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/address/model/person/TeacherTest.java
Labels: priority.High

#193 Update user guide and developer guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.High

#277 Fix PE-D bugs in UG
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/helpMessage.png
Labels: type.UserGuide

#279 PE-D Edit emergency contact fix
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
Labels: type.Bug, type.FeatureFlaw

#286 PE-D: Update email field validation to allow consecutive symbols
  src/main/java/seedu/address/model/person/Email.java
  src/test/java/seedu/address/model/person/EmailTest.java
Labels: type.Bug, bug.UI

#287 PE-D: Rename AddressBook to EduConnect in logger
  src/main/java/seedu/address/MainApp.java
Labels: type.Bug, priority.Low

#280 PE-D: Fix bug with editting subjects
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
Labels: type.Bug

#284 PE-D: Update user guide
  README.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/EditCommand.png
  docs/images/SortAttendanceCommand.png
Labels: type.UserGuide

#292 PE-D: Move "How to" down and add Find command behavior
  docs/UserGuide.md
Labels: type.UserGuide

#283 PE-D: Fix grammatical errors and missing information in messages
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: bug.UI

#282 PE-D: Fix input validation for Classes field for Teacher
  src/main/java/seedu/address/logic/parser/AddTeacherCommandParser.java
Labels: type.Bug

#294 PE-D: Update duplicate person message to be more general
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddStudentCommand.java
  src/main/java/seedu/address/logic/commands/AddTeacherCommand.java
  src/test/java/seedu/address/logic/commands/AddStudentCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTeacherCommandTest.java
Labels: type.Bug, bug.UI

#299 PE-D: Update message constraints for name and phone
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Phone.java
Labels: type.Bug, priority.Low, bug.UI

#303 Minor issues in user guide
  docs/UserGuide.md
Labels: priority.High

#298 PE-D: Add duplicate prefix check for add Student command
  src/main/java/seedu/address/logic/parser/AddStudentCommandParser.java
  src/main/java/seedu/address/logic/parser/AddTeacherCommandParser.java
Labels: type.Bug, priority.Low

#310 Add details to Planned Enhancements 1-3
  docs/DeveloperGuide.md
Labels: priority.High, type.DeveloperGuide
